version: '3.8'

services:

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - NODE_ENV=DEVELOPMENT
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:dev:docker"
    restart: unless-stopped

  db:
    image: postgres:17.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma-studio:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./Backend:/app
    ports:
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - NODE_ENV=development
    depends_on:
      - db
    command: npx prisma studio

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    env_file:
      - ./Frontend/.env
    command: sh -c "npm run dev -- --host"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
